apiVersion: apps/v1
kind: Deployment
metadata:
  name: bioacoustics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bioacoustics-api
  template:
    metadata:
      labels:
        app: bioacoustics-api
    spec:
      containers:
      - name: bioacoustics-api
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
        command: ["gunicorn"]
        args: ["--bind", "0.0.0.0:8000", "--access-logfile", "-", "bioacoustics.wsgi:application"]
        env:
        - name: POSTGRES_HOST
          value: "bioacoustics-db"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: POSTGRES_DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret-key
              key: django_secret_key
        - name: MILVUS_DB_HOST
          value: "milvus"
        - name: MILVUS_DB_USER
          valueFrom:
            secretKeyRef:
              name: milvus-credentials
              key: username
        - name: MILVUS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: milvus-credentials
              key: password
        - name: MINIO_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_SERVER_URL
        - name: MINIO_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_BUCKET_NAME
        - name: MINIO_BUCKET_LOCATION
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_BUCKET_LOCATION
              optional: true
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_SECRET_KEY
        - name: MINIO_SSL_SUPPORTED
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_SSL_SUPPORTED
              optional: true
        - name: EMBED_SERVICE_URL
          value: {{ .Values.config.embedServiceUrl }}
        ports:
        - containerPort: 8000
      nodeSelector:
      imagePullSecrets:
      - name: a2o-search-prod-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: bioacoustics-api-service
spec:
  selector:
    app: bioacoustics-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
